### ISSUE TITLE
The url params within the RouteContext cannot be used by a parent middleware 

### ISSUE THREAD

**Issue by mpholcomb** [pressly/chi#127]
This may be intended, but you cannot register a top-level|parent middleware that utilizes URLParams since they are not available until after the Route is defined that introduces those variables.  The use case that I currently would have for such a thing is to auto-generate a role string used for authorization.  Such as:

The programmer defines that the route requires "http:get|/some/route/:withavar".
The user has the role "http:get|/some/route/123".
And the route is defined as "/some/route/:withavar".

This generic middleware could find the `withavar` on the URLParams and use that to create the expanded role to verify authorization.

It would be great to have the route variables parsed before the middleware is executed.

```
package main

import (
	"fmt"
	"net/http"

	"github.com/pressly/chi"
	"github.com/pressly/chi/render"
)

func main() {
	r := chi.NewRouter()
	r.Use(Handler("before"))
	r.Route("/:testVar", func(r chi.Router) {
		r.Use(Handler("within"))
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		})
	})

	http.ListenAndServe(":8080", r)
}

func Handler(note string) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			rctx := chi.RouteContext(r.Context())
			render.PlainText(w, r, fmt.Sprintf("%s: %+v\n", note, rctx.URLParams))
			next.ServeHTTP(w, r)
		})
	}
}
```

**Comment by mpholcomb** [comment]
I should have mentioned, that instead of using the actual variables, I am just using the full req.URL to generate the url roles, which is certainly OK.  I may be creating a synthetic use case here.

**Comment by pkieltyka** [comment]
@mpholcomb I see what you mean. You'd like to see URLParams initialized and at the very top of the routing path. Unfortunately this won't work by the design of chi's tree. It might be possible to do a first-pass through the routing tree just to determine the urlparams, and then again to actually call the handler, but I don't like that solution. I'll keep it in mind when I'm solving #78 - but think it would be quite a stretch because the URLParams might best stay built on the execution path.

Im not sure if using param key is a good way to be supporting rule signatures. We've implemented an ACL router on top of chi.Router internally at Pressly (which I'd like to polish and open source someday), it looks like this: https://gist.github.com/pkieltyka/ac40ab917470e6d0c8e951b49b22d497

That implementation is incomplete but might give you some ideas. What it does is build an acl path according to the structure of the tree by injecting middlewares that set a `acl.route` value on the context.

in the end it looks like..

```go
r := acl.NewRouter("hubs")

r.Get("/", ListHubs)
r.Post("/", CreateHub)
r.Get("/following", ListFollowedHubs)

r.Route("/:hubId", func(r chi.Router) {
	r.Use(HubCtx)
	r.Use(PublicHubPermissions)
	r.Use(SecretHubPermissions)

	r.Get("/", GetHub)
	r.Put("/", UpdateHub)
	r.Delete("/", DeleteHub)
	r.Post("/upgrade", UpgradeHub)
	r.Get("/tags", ListHubTags)

	r.Route("/users", func(r chi.Router) {
		r.Use(acl.Route("users"))
		r.Mount("/", access.Routes())
		r.Get("/", ListUsers)
		r.Post("/", JoinHub)
	})

	// ...etc..
})
```

as request path, the ResourceControl make sure to check a user permissions context value and tests the acl routing path and either keeps going, on stops. 

We thought a lot of this as permissions in a filesystem.

**Comment by mpholcomb** [comment]
Yeah I agree about the double pass through the tree would just slow down the router.  Thanks for the thoughts behind the acl.route.  For now, I am checking the role based on the url, which is really similar to your acl.  I will go ahead and close this.  Thanks again!

**Comment by VojtechVitek** [comment]
See https://github.com/pressly/chi/issues/125#issuecomment-270416138 for ACL-middleware approach.
