### ISSUE TITLE
Middlewares not called on NotFound handler

### ISSUE THREAD

**Issue by gpopovic** [pressly/chi#163]
Currently, middlewares are not calle when NotFound handler is executed.

Is this a design choice? and is there a way to achieve that functionality?

**Comment by pkieltyka** [comment]
Hey Goran, yea this is intended and by design. If you really want it, you could make. Separate chain of middlewares with chi.Chain(mw1, mw2) and pass the request through in NotFound. 

Or try to make a top level subrouter, mount on "/*" a new subrouter with your actual routes. I believe the MW in the top router will execute.

**Comment by gpopovic** [comment]
@pkieltyka thanks :+1:

**Comment by gpopovic** [comment]
@pkieltyka  are you sure middlewares are not called? I tested now ..and it seems that middlewares ARE called .

My router looks like this

	```
app.Router.NotFound(app.NotFound)
	app.Router.Use(app.WithLogger)
	app.Router.MethodNotAllowed(app.MethodNotAllowed)

	app.Router.Post("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("AAAAAAAAAA"))
	})
```

And i get logging line on every 404 and 405

**Comment by pkieltyka** [comment]
Interesting, perhaps they are then. The behavior changed from v1 to v2 so I just don't recall at this time. But given your example it looks like the middleware stack is called, which would be my initially thought it the ticket title threw me off a bit. I'm away this week but let me know.

**Comment by gpopovic** [comment]
Ok so i can confirm, middlewares are called..but i noticed another bug..I'll open the issue for that
