### ISSUE TITLE
graceful shutdown?

### ISSUE THREAD

**Issue by alinz** [pressly/chi#18]
@pkieltyka, How would you implement graceful feature for shutdown? Do we need it? If not, how would you implement this feature along side with chi?

**Comment by pkieltyka** [comment]
@alinz well, chi's router implements http.Handler, so you can use a third party graceful shutdown package like https://github.com/tylerb/graceful or like we do in the Pressly API using goji's graceful package with chi: https://github.com/zenazn/goji/tree/master/graceful

once nice thing to trigger a ctx.Done via the cancelFunc from a context when a shutdown is called. I have a trick in imgry where I do this..

https://github.com/pressly/imgry/blob/master/cmd/imgry-server/main.go#L38-L41
https://github.com/pressly/imgry/blob/master/server/server.go#L95
https://github.com/pressly/imgry/blob/master/server/middleware.go#L16-L26

the above example works by having a server-wide context, and replace the context in the chain with this one by copying the urlparams first. I thought, maybe we could have a parent ctx on the router itself, but, didn't think of an elegant enough solution for it and too busy to find one since this works.

**Comment by alinz** [comment]
Awesome! thanks!

**Comment by pkieltyka** [comment]
no prob. let's keep it open for a bit in case others have the same question.
