### ISSUE TITLE
Proper Use of Timeout middleware

### ISSUE THREAD

**Issue by mihai-tiriplica-hs** [pressly/chi#198]
The example for Timeout middleware doesn't really follow a normal usecase - handlers don't usually write on channels. I'm not sure how can I write a handler so that a timeout response will be returned.

If it helps this is my code:

```go
package main

import (
	"net/http"
	"time"

	"github.com/pressly/chi"
	"github.com/pressly/chi/middleware"
	"gopkg.in/tylerb/graceful.v1"
)


const Timeout = 60 // Number of seconds to wait for a request to finish


func GetHandler(w http.ResponseWriter, r *http.Request) {
	time.Sleep(10 * time.Second)
	w.Write([]byte("welcome"))
}


func main() {
	router := chi.NewRouter()
	router.Use(middleware.Logger)
	router.Use(middleware.CloseNotify)
	router.Use(middleware.Timeout(2 * time.Second))

	router.Get("/", GetHandler)

	srv := &graceful.Server{
		Timeout: Timeout * time.Second,
		Server:  &http.Server{Addr: ":3000", Handler: router},
	}

	srv.ListenAndServe()
}
```

Thank you!

**Comment by VojtechVitek** [comment]
`middleware.Timeout(2 * time.Second)` sets timeout on `r.Context()`. After the timeout is reached, the context is canceled. You need to pass this context to the underlying logic to leverage the cancelation functionality.

Some examples:
- select on multiple channels, if you can receive processed data via channel, as in [example code](https://github.com/pressly/chi/blob/master/_examples/limits/main.go#L64-L71)
- HTTP request https://golang.org/pkg/net/http/#Request.WithContext
- SQL query https://golang.org/pkg/database/sql/#DB.QueryContext
- pass the ctx as a first argument to the underlying functions, so you can listen on ctx.Done()
     `func HeavyWork(ctx context.Context, ...)`

**Comment by pkieltyka** [comment]
hey @mihai-tiriplica-hs as @VojtechVitek mentioned, the `context.Context` really just signals to other contexts that the timeout has been reached, you have to stop processing on your own.

Some examples: https://github.com/pressly/chi/blob/master/_examples/limits/main.go#L58-L73
and for graceful shutdown: https://github.com/pressly/chi/blob/master/_examples/graceful/main.go

**Comment by mihai-tiriplica-hs** [comment]
Got it, it was not very clear to me in the first place (not a lot of Go experience). Thank you!

**Comment by tiriplicamihai** [comment]
Coming back to this question (sorry for dual identity, the first one is the work account), I think there can be some improvements for the timeouts. For example, if the timeout is set to 30 seconds and I have an external call that takes 29 seconds and my processing takes 2 seconds then, if I understand correctly, no timeout will be raised even though the request took 31 seconds.
I read this article: https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/ and rewrote the hello world server as:

```go
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/pressly/chi"
	"github.com/pressly/chi/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.Logger)
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(10 * time.Second)
		w.Write([]byte("hello world"))
	})

	server := &http.Server{Addr: ":3333", Handler: r, ReadTimeout: 2 * time.Second, WriteTimeout: 2 * time.Second}
	fmt.Println(server.ListenAndServe())
}
```

Now the connection seems to close but the request processing does not stop. I was looking now into using [TimeoutHandler](https://golang.org/pkg/net/http/#TimeoutHandler) too but I'm not sure how it can be used along with chi since I can't really pass a Handler to the "Get" method and the "mux.handle" method is private. Also, is it a good idea to use it considering it runs the handler in a go routine? I can rewrite it as a middleware if this is the case.

Thanks again!

**Comment by Tom29** [comment]
@tiriplicamihai by doing this, we can serve only 2s for one request.
what happen with requests like uploading? Any chance to set timeout for each route?

**Comment by demaggus83** [comment]
This middleware should do the trick.

```go
// TimeoutHandler is a middleware to add http.TimeoutHandler.
func TimeoutHandler(timeout time.Duration) func(next http.Handler) http.Handler {
    return func(next http.Handler) http.Handler {
        return http.TimeoutHandler(next, timeout, "Timeout.")
    }
}
```

```go
mux.Route("/api", func(r chi.Router) {
    // giving the handler 1/2 of WriteTimeout time to handle
    timeout := time.Duration(float64(config.WriteTimeout) * 0.5)
    r.Use(webserver.TimeoutHandler(timeout))
    // ...
}
```
