### ISSUE TITLE
Add support for fasthttp

### ISSUE THREAD

**Issue by hmgle** [pressly/chi#39]
`fasthttp` provides some considerable performance improvements.

I had forked [chi](https://github.com/hmgle/chi/tree/fasthttp) and make it work for `fasthttp`. The result of the [benchmark](https://github.com/hmgle/web-framework-benchmark/blob/master/results.txt#L77) on my host show that `chi/fasthttp` is very close to `echo/fasthttp` and [iris](https://github.com/kataras/iris):

- chi/fasthttp

```
benchmarking chi...
Running 10s test @ http://localhost:8080/teams/x-men/members/wolverine
  2 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.00ms    2.40ms  28.22ms   89.64%
    Req/Sec    53.71k     6.43k   72.56k    69.50%
  1076944 requests in 10.09s, 167.41MB read
Requests/sec: 106702.11
Transfer/sec:     16.59MB
benchmarking with pipleline...
Running 10s test @ http://localhost:8080
  2 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.80ms    7.96ms 124.13ms   84.49%
    Req/Sec   266.17k    16.76k  320.25k    74.50%
  5299709 requests in 10.01s, 823.83MB read
Requests/sec: 529503.08
Transfer/sec:     82.31MB
```

- echo/fasthttp

```
benchmarking echo/fasthttp...
Running 10s test @ http://localhost:8080/teams/x-men/members/wolverine
  2 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.99ms    2.32ms  22.67ms   89.44%
    Req/Sec    53.56k     6.64k   90.73k    74.37%
  1070567 requests in 10.09s, 166.42MB read
Requests/sec: 106122.28
Transfer/sec:     16.50MB
benchmarking with pipleline...
Running 10s test @ http://localhost:8080
  2 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.99ms    7.70ms 131.53ms   83.88%
    Req/Sec   232.53k    14.14k  273.31k    72.50%
  4630831 requests in 10.01s, 719.86MB read
Requests/sec: 462480.63
Transfer/sec:     71.89MB
```

Would you like to add one branch for fasthttp?

**Comment by VojtechVitek** [comment]
@hmgle thanks for the investigation and really interesting benchmarks!

I think having fork for fasthttp would be the best option here right now, though.

We're really excited about Go 1.7's built-in context, which will allow us to simplify chi, remove `interface{}` args and use the standard http.Handler signatures:
```go
func Handler(w http.ResponseWriter, r *http.Request) {
   user, ok := r.Context().Value("user")
   // do something
})
```
Please, check out https://github.com/pressly/chi/tree/v2 branch.

---

If we were to support fasthttp and its custom signatures `func(ctx context.Context, fctx *fasthttp.RequestCtx)`, we'd have to maintain a lot more again.

Fasthttp seems to be really fast, but I wonder about missing HTTP 2 support and Go 1.7's request context.

We may have fasthttp as a chi subpkg one day. But I doubt it could happen anytime soon because of maintainability issues.
```go
import "github.com/pressly/chi/fasthttp

func main() {
  r := chi.NewRouter()

  r.Get("/", func(ctx context.Context, fctx *fasthttp.RequestCtx) {
    w.Write([]byte("hi"))
  })

  http.ListenAndServe(":3333", r)
}
```

**Comment by hmgle** [comment]
@VojtechVitek I agree.
Fasthttp had the advantage of a good performance, but at the same time it is incompatible with `net/http`. It would not benefit from `net/http` standardization.
