### ISSUE TITLE
Using Mux.pool

### ISSUE THREAD

**Issue by lofcek** [pressly/chi#51]
Hello, I'm using your http router chi. I like it some much, but there are several thing that I don't understand at all. Could you explain me that?

1. Mux.pool is a pool of chi.Context. If I understood well, only reason why, is you are trying to have less allocation. But If this is true, why you don't have just one global pool for every Mux? It should not be more interesting share bigger structures like Mux into pool?
2. In Mux.Group you again create new Mux - that should be copy of previous one. But it does not have initialized pool (neither shared with parent, nor created new). Is it good?
3. In Mux.ServeHTTPC you use pool.Get() to obtain new Context. After that, next handler is called and at the end, context is reseted and return back to pool. It sound good, but if appeared some panic during next handler, context won't be returned back. Is it an intention or mistake?

**Comment by pkieltyka** [comment]
@lofcek thanks for the questions. There's been a lot of thought put into the design, but I am still not completely settled on the zero-alloc router implementation but I will certainly have it nailed down in the v2 branch once I figure it out.

1. The Mux.pool is a pool for chi.Context's like you said, the chi.Context is the routing context where we store params and other routing-related details on the request context. Chi is designed to handle a nesting of Mux's as subrouters mounted together (as I'm sure you know). However, its just the first Mux that will either get/set a routing context from the pool, just the single time. The other Mux's are just passed down the value so they dont need to use their pools, unless they are somehow mounted independently and its they are the top-level mux.

2. Yes, I make a new mux per Group, the memory is allocated just once when the routes are built, the memory footprint is small, and it wouldnt make a new routing context since it would receive it from the top level. Btw, I am still trying to figure out the right name for the Group() method (I'm planning to rename it), because as you can see this is really used to define a new inline mux that starts a new middleware chain for a group of routes. It's very close to Route(), although Route() accepts a pattern as the first argument, whereas Group() mounts the router inline. Other names that come to mind for Group() could be.. Inline(),  Attach(), MiddlewareGroup(), UseInline(), ... 

3. Yea, I really don't like this code, but I personally don't see a better way, If you can produce a test case that causes this to fail let me know. In v2 there is no more ServeHTTPC method, so the problem changes

**Comment by lofcek** [comment]
1. Ok
2. I agree, that Group is bit confusing name, but I think the best from those you mentioned. Can we somehow ask other project participants? My personal favorites will be Group, InlineRoute, MiddlewareGroup, maybe Attach. Inline/UseInline is confusing.

 I also saw identifier inline as a flag inside Mux. This is the worst case give the same thing two different names. 

3. Why don't use defer?
```
// ServeHTTPC is chi's Handler method that adds a context.Context argument to the
// standard ServeHTTP handler function.
func (mx *Mux) ServeHTTPC(ctx context.Context, w http.ResponseWriter, r *http.Request) {
    returnContext := func(ctx *Context) {
           ctx.reset()
           mx.pool.Put(rctx)
    }
    if ctx == nil {
        rctx = mx.pool.Get().(*Context)
        defer returnContext(ctx)
        ctx = rctx
    } else if rctx, ok := ctx.(*Context); !ok {
        if rctx, ok = ctx.Value(routeCtxKey).(*Context); !ok {
            rctx = mx.pool.Get().(*Context)
            defer returnContext(rctx)
            ctx = context.WithValue(ctx, routeCtxKey, rctx)
        }
    }

    mx.handler.ServeHTTPC(ctx, w, r)
}

```

**Comment by pkieltyka** [comment]
2. I'll ask the other guys too, good idea. I have been thinking and leaning towards the method `Inline()`, but lets see where the consensus lands

3. Defer has a cost, and the current code works, so I'd rather not change it. In v2, this becomes different which is my primary focus aside from bugs in v1

**Comment by aboukirev** [comment]
A better term for what you call Group is Junction, albeit it's a longer name. If you are into biological taxonomy, you could use Clade.

**Comment by lofcek** [comment]
If you decide not to use defer, than please close the issue and open new one with better name for Group. I also have a new favorite - GroupHandlers.
