### ISSUE TITLE
wildcards router not working when path conflict

### ISSUE THREAD

**Issue by chenjie4255** [pressly/chi#80]
hi, now I am using chi on golang 1.7, I meet such a problem:

```
	r := chi.NewRouter()

	// A good base middleware stack
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	r.Options("/*", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hi"))
	})

	r.Get("/foo", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("foo"))
	})

	http.ListenAndServe(":3333", r)

```

a options request for ```"/foo"``` just return 405 method not allow.......:(

**Comment by pkieltyka** [comment]
hey @chenjie4255 - the reason is because the `r.Options("/*", h)` will route will match everything other than "/foo", that is a wildcard route path that will match routes that don't match any other static routes like "/foo". Give it a try on a path like `/blahafsd` and you'll see the OPTIONS request will return 200.

if you are trying to capture every OPTIONS request then I recommend you instead create a middleware such as..

```go
func AllOptions(next http.Handler) http.Handler {
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    if r.Method == "OPTIONS" {
      // your logic..
      // w.Write(yourResponse)
      return // we return because likely we want to finish the request here.
    }
    next.ServeHTTP(w, r) // keep processing for non-OPTIONS methods
  })
}
```
then `r.Use(AllOptions)` after the Recoverer

are you trying to do some cors stuff..? have a look at https://github.com/goware/cors
