### ISSUE TITLE
Configurable logger middleware

### ISSUE THREAD

**Issue by mvdan** [pressly/chi#95]
The middlewares in the repo work really well, cheers for that.

I use chi to serve dynamic content as well as static content. I have the logger middleware set up on the whole thing, which is good but it's too verbose for static content.

I thought about enabling it only for non-static content, but I would still like to get logs about 4XX's (and possibly 5XX's?) on the static content, for example if a link to an image is broken.

As far as I can tell the logger middleware isn't configurable, but some others are. A few options come to mind:

* Fork the middleware and create a new configurable middleware (e.g. with a `mode` flag that tells it what is to be logged) - this would mean code duplication, as far as I can tell
* Modify the current middleware - is this possible? I assume not, thinking that with v2 the api is frozen.
* Make the middlewares extendible at some level to enable modifications and tweaks like these - don't know if this makes sense at all

Also, I was thinking that chi would really benefit from a "contrib" middleware repo. Kind of like what `golang.org/x/` is to `std`. Only add to `chi` what is really basic and important, and the rest can live in a separate repo like `chi-contrib` where the community plays a bigger part. This would also allow changing the API of certain middlewares without breaking backwards compatibility, as these would not be released in tags along with the main repo.

**Comment by pkieltyka** [comment]
hey @mvdan thanks man, we've worked hard to keep middleware lean and robust. 

I agree the middleware logger doesn't fit all needs, especially lacking structured logging. The nice thing about chi is that its fully compatible with the stdlib, and any other handler or middleware in the ecosystem that as well uses just the stdlib, that is `http.Handler` or `func(http.Handler) http.Handler` and `r.Context()` from *http.Request. Therefore you could write a logger in any repo, and it would 'just work' in chi, as well work perfectly well for any other Go project that uses vanilla http.Handler's :) 

So far, we have used https://github.com/goware as our "contrib" for chi, since its really not chi specific, nothing is chi specific, its Go net/http specific

**Comment by mvdan** [comment]
Oh, makes sense. In that case, I think the README should be modified to clarify that any `net/http` middleware will work with chi. Right now it only mentions `chi middleware` and lists middlewares developed alongside chi, so this wasn't obvious to me.

Thanks!

**Comment by pkieltyka** [comment]
Ok cool, thanks for the feedback, I'll make sure to clarify in the README

**Comment by pkieltyka** [comment]
@mvdan https://github.com/pressly/chi/commit/2fb5424b313fbe427e2e337f20f2b45535ca3e0a -- please let me know if thats better and if there are other parts in the docs that could be better or parts you feel are missing or under-represented. thanks!
